<!-- ViciOne modification: WP-F2-SERVICEBUS-IDENTITY, 2026-08-07. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.DapperIntegration</PackageId>
    <Title>ViciOne.ServiceBus.DapperIntegration</Title>
    <PackageTags>ViciOne.ServiceBus;Dapper</PackageTags>
    <Description>ViciOne.ServiceBus Dapper persistence support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="dapper.contrib" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>
