<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../signing.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <PackageTags>ViciOne.ServiceBus;Testing</PackageTags>
    <Description>Transport-independent test harness and test-support APIs for ViciOne.ServiceBus applications.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.ServiceBus.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100e9e6f2f380b10f7b8f2ef6ae0e241e612d363d34b68936c7eeea11d727581d583a6449d989200db64c080f5d55c4bdb60c4ffa8c6648023290150b325e567b13ebe83e394b7374d9ab36874a0d7e2718290433eb1a03f1d4c465388a27acfd2888ea2c762921853e19ae89d689c6caacdfbeb566c20ca5f46ed621e6a7332087" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ViciOne.ServiceBus.Courier\ViciOne.ServiceBus.Courier.csproj" />
    <ProjectReference Include="..\ViciOne.ServiceBus.Futures\ViciOne.ServiceBus.Futures.csproj" />
    <ProjectReference Include="..\ViciOne.ServiceBus.Mediator\ViciOne.ServiceBus.Mediator.csproj" />
    <ProjectReference Include="..\ViciOne.ServiceBus.Sagas\ViciOne.ServiceBus.Sagas.csproj" />
    <ProjectReference Include="..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>
</Project>
