<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../signing.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.Newtonsoft</PackageId>
    <Title>ViciOne.ServiceBus.Newtonsoft</Title>
    <PackageTags>ViciOne.ServiceBus;Newtonsoft;JSON.NET</PackageTags>
    <Description>ViciOne.ServiceBus Newtonsoft JSON/BSON support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Newtonsoft.Json.Bson" />
  </ItemGroup>

</Project>
