<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ViciOne.ServiceBus.EntityFrameworkCore</RootNamespace>
    <PackageId>ViciOne.ServiceBus.EntityFrameworkCore.Sagas</PackageId>
    <Title>ViciOne.ServiceBus.EntityFrameworkCore.Sagas</Title>
    <PackageTags>ViciOne.ServiceBus;EF;EFCore;EntityFramework;EntityFrameworkCore;Sagas</PackageTags>
    <Description>ViciOne.ServiceBus Entity Framework Core saga, future, and job persistence support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ViciOne.ServiceBus.EntityFrameworkCore/ViciOne.ServiceBus.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../ViciOne.ServiceBus.Futures/ViciOne.ServiceBus.Futures.csproj" />
    <ProjectReference Include="../../ViciOne.ServiceBus.JobService/ViciOne.ServiceBus.JobService.csproj" />
    <ProjectReference Include="../../ViciOne.ServiceBus.Sagas/ViciOne.ServiceBus.Sagas.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.ServiceBus.EntityFrameworkCore.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100e9e6f2f380b10f7b8f2ef6ae0e241e612d363d34b68936c7eeea11d727581d583a6449d989200db64c080f5d55c4bdb60c4ffa8c6648023290150b325e567b13ebe83e394b7374d9ab36874a0d7e2718290433eb1a03f1d4c465388a27acfd2888ea2c762921853e19ae89d689c6caacdfbeb566c20ca5f46ed621e6a7332087" />
    <InternalsVisibleTo Include="ViciOne.ServiceBus.EntityFrameworkCore.LocalIntegration.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100e9e6f2f380b10f7b8f2ef6ae0e241e612d363d34b68936c7eeea11d727581d583a6449d989200db64c080f5d55c4bdb60c4ffa8c6648023290150b325e567b13ebe83e394b7374d9ab36874a0d7e2718290433eb1a03f1d4c465388a27acfd2888ea2c762921853e19ae89d689c6caacdfbeb566c20ca5f46ed621e6a7332087" />
  </ItemGroup>
</Project>
