<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.Quartz</PackageId>
    <Title>ViciOne.ServiceBus.Quartz</Title>
    <PackageTags>ViciOne.ServiceBus;Quartz;Scheduler;Scheduling</PackageTags>
    <Description>ViciOne.ServiceBus Quartz.NET scheduler support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>
</Project>
