<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ViciOne.ServiceBus.Abstractions/ViciOne.ServiceBus.Abstractions.csproj" />
    <ProjectReference Include="../Testing/ViciOne.ServiceBus.Tests.Infrastructure/ViciOne.ServiceBus.Tests.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Requirements/AbstractionsLocalIntegrationRequirements.json" />
    <EmbeddedResource
      Include="Requirements/AbstractionsLocalIntegrationRequirements.json"
      LogicalName="ViciOne.ServiceBus.Abstractions.LocalIntegration.Tests.Requirements.AbstractionsLocalIntegrationRequirements.json" />
  </ItemGroup>

</Project>
