<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.Azure.Cosmos.Table</PackageId>
    <Title>ViciOne.ServiceBus.Azure.Cosmos.Table</Title>
    <PackageTags>ViciOne.ServiceBus;Azure;Cosmos;Table</PackageTags>
    <Description>ViciOne.ServiceBus Azure Cosmos persistence support; $(Description)</Description>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Data.Tables" />
    </ItemGroup>

</Project>
