<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.SqlTransport.SqlServer</PackageId>
    <Title>ViciOne.ServiceBus.SqlTransport.SQL Server</Title>
    <PackageTags>ViciOne.ServiceBus;Database;Transport;SQL Server;Microsoft;Azure;SQL</PackageTags>
    <Description>ViciOne.ServiceBus SQL Server Transport; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>
</Project>
