<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ViciOne.ServiceBus.SqlTransport.PostgreSql</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.SqlTransport.PostgreSql</PackageId>
    <Title>ViciOne.ServiceBus.SqlTransport.PostgreSql</Title>
    <PackageTags>ViciOne.ServiceBus;Database;Transport;PostgreSQL;npgsql</PackageTags>
    <Description>ViciOne.ServiceBus PostgreSQL Database Transport; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>

</Project>
