<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ViciOne.ServiceBus.SqlTransport.PostgreSql</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.SqlTransport.PostgreSql</PackageId>
    <Title>ViciOne.ServiceBus.SqlTransport.PostgreSql</Title>
    <PackageTags>ViciOne.ServiceBus;Database;Transport;PostgreSQL;npgsql</PackageTags>
    <Description>PostgreSQL-backed queue and topic transport integration for ViciOne.ServiceBus.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ViciOne.ServiceBus.SqlTransport\ViciOne.ServiceBus.SqlTransport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.ServiceBus.SqlTransport.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100e9e6f2f380b10f7b8f2ef6ae0e241e612d363d34b68936c7eeea11d727581d583a6449d989200db64c080f5d55c4bdb60c4ffa8c6648023290150b325e567b13ebe83e394b7374d9ab36874a0d7e2718290433eb1a03f1d4c465388a27acfd2888ea2c762921853e19ae89d689c6caacdfbeb566c20ca5f46ed621e6a7332087" />
    <InternalsVisibleTo Include="ViciOne.ServiceBus.SqlTransport.PostgreSql.LocalIntegration.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100e9e6f2f380b10f7b8f2ef6ae0e241e612d363d34b68936c7eeea11d727581d583a6449d989200db64c080f5d55c4bdb60c4ffa8c6648023290150b325e567b13ebe83e394b7374d9ab36874a0d7e2718290433eb1a03f1d4c465388a27acfd2888ea2c762921853e19ae89d689c6caacdfbeb566c20ca5f46ed621e6a7332087" />
  </ItemGroup>

</Project>
