<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Persistence/ViciOne.ServiceBus.AmazonS3/ViciOne.ServiceBus.AmazonS3.csproj" />
    <ProjectReference Include="../../Testing/ViciOne.ServiceBus.Tests.Infrastructure/ViciOne.ServiceBus.Tests.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Requirements/AmazonS3LocalIntegrationRequirements.json" />
    <EmbeddedResource
      Include="Requirements/AmazonS3LocalIntegrationRequirements.json"
      LogicalName="ViciOne.ServiceBus.AmazonS3.LocalIntegration.Tests.Requirements.AmazonS3LocalIntegrationRequirements.json" />
  </ItemGroup>
</Project>
