<!-- ViciOne modification: WP-F2-SERVICEBUS-IDENTITY, 2026-08-07. -->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>ViciOne.ServiceBus</RootNamespace>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.WebJobs.ServiceBus</PackageId>
    <Title>ViciOne.ServiceBus.WebJobs.ServiceBus</Title>
    <PackageTags>ViciOne.ServiceBus;Azure;WebJobs;AzureFunctions</PackageTags>
    <Description>ViciOne.ServiceBus Azure WebJobs Service Bus support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" />
    <ProjectReference Include="..\ViciOne.ServiceBus.Azure.ServiceBus.Core\ViciOne.ServiceBus.Azure.ServiceBus.Core.csproj" />
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>
</Project>
