<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.Azure.ServiceBus.Core\ViciOne.ServiceBus.Azure.ServiceBus.Core.csproj" />
    <ProjectReference Include="..\..\src\Scheduling\ViciOne.ServiceBus.QuartzIntegration\ViciOne.ServiceBus.QuartzIntegration.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus.TestFramework\ViciOne.ServiceBus.TestFramework.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
    <ProjectReference Include="..\..\src\Persistence\ViciOne.ServiceBus.Azure.Storage\ViciOne.ServiceBus.Azure.Storage.csproj" />
  </ItemGroup>

</Project>
