<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/ViciOne.ServiceBus/ViciOne.ServiceBus.csproj" />
    <ProjectReference Include="../../../src/Transports/ViciOne.ServiceBus.SqlTransport.PostgreSql/ViciOne.ServiceBus.SqlTransport.PostgreSql.csproj" />
    <ProjectReference Include="../../../src/Transports/ViciOne.ServiceBus.SqlTransport.SqlServer/ViciOne.ServiceBus.SqlTransport.SqlServer.csproj" />
    <ProjectReference Include="../../Testing/ViciOne.ServiceBus.Tests.Infrastructure/ViciOne.ServiceBus.Tests.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Requirements/SqlTransportRequirements.json" />
    <EmbeddedResource
      Include="Requirements/SqlTransportRequirements.json"
      LogicalName="ViciOne.ServiceBus.SqlTransport.Tests.Requirements.SqlTransportRequirements.json" />
  </ItemGroup>
</Project>
