<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Nullable>annotations</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>False</IsPackable>
    <IsTestProject>False</IsTestProject>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <AssemblyName>vicione-servicebus-benchmark</AssemblyName>
    <RootNamespace>ViciOneServiceBusBenchmark</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Persistence\ViciOne.ServiceBus.EntityFrameworkCore\ViciOne.ServiceBus.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Persistence\ViciOne.ServiceBus.EntityFrameworkCore.Sagas\ViciOne.ServiceBus.EntityFrameworkCore.Sagas.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus.Mediator\ViciOne.ServiceBus.Mediator.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus.Testing\ViciOne.ServiceBus.Testing.csproj" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.ActiveMq\ViciOne.ServiceBus.ActiveMq.csproj" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.AmazonSqs\ViciOne.ServiceBus.AmazonSqs.csproj" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.AzureServiceBus\ViciOne.ServiceBus.AzureServiceBus.csproj" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.RabbitMq\ViciOne.ServiceBus.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
    <ProjectReference Include="..\..\src\Transports\ViciOne.ServiceBus.SqlTransport.PostgreSql\ViciOne.ServiceBus.SqlTransport.PostgreSql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.ServiceBus.Benchmark.Tests" />
  </ItemGroup>
</Project>
