#:package Microsoft.CodeAnalysis.CSharp
#:property Nullable=enable
#:property ImplicitUsings=enable
#:property PublishAot=false
#:property NuGetLockFilePath=AnnotateNullDefaults.packages.lock.json

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

if (args.Length is < 1 or > 2 || !Directory.Exists(args[0]) || args.Length == 2 && !File.Exists(args[1]))
{
    Console.Error.WriteLine("Usage: dotnet run AnnotateNullDefaults.cs -- <source-directory> [compiler-log]");
    return 2;
}

var root = Path.GetFullPath(args[0]);
var diagnostics = args.Length == 2 ? ReadDefaultDiagnostics(args[1]) : new Dictionary<string, List<(int Line, int Column)>>(StringComparer.Ordinal);
var updatedFiles = 0;
var updatedParameters = 0;

foreach (var path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)
             .Where(path => !ContainsBuildDirectory(path)))
{
    var original = await File.ReadAllTextAsync(path);
    if (original.StartsWith("// <auto-generated/>", StringComparison.Ordinal))
        continue;

    var tree = CSharpSyntaxTree.ParseText(original, CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview));
    var compilationUnit = (CompilationUnitSyntax)await tree.GetRootAsync();
    var positions = diagnostics.TryGetValue(Path.GetFullPath(path), out var fileDiagnostics)
        ? fileDiagnostics.Select(item => tree.GetText().Lines[item.Line - 1].Start + item.Column - 1).ToHashSet()
        : [];
    var rewriter = new NullDefaultRewriter(positions);
    var updated = (CompilationUnitSyntax)rewriter.Visit(compilationUnit)!;

    if (rewriter.ChangeCount == 0)
        continue;

    await File.WriteAllTextAsync(path, updated.ToFullString());
    updatedFiles++;
    updatedParameters += rewriter.ChangeCount;
}

Console.WriteLine($"Annotated {updatedParameters} null-default parameters across {updatedFiles} files.");
return 0;

static bool ContainsBuildDirectory(string path)
{
    var segments = path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
    return segments.Contains("bin", StringComparer.Ordinal) || segments.Contains("obj", StringComparer.Ordinal);
}

static Dictionary<string, List<(int Line, int Column)>> ReadDefaultDiagnostics(string logPath)
{
    var result = new Dictionary<string, List<(int Line, int Column)>>(StringComparer.Ordinal);
    var pattern = new System.Text.RegularExpressions.Regex(@"^(?<path>.*\.cs)\((?<line>\d+),(?<column>\d+)\): error CS8625:");
    foreach (var line in File.ReadLines(logPath))
    {
        var match = pattern.Match(line);
        if (!match.Success)
            continue;

        var path = Path.GetFullPath(match.Groups["path"].Value);
        if (!result.TryGetValue(path, out var positions))
            result.Add(path, positions = []);
        positions.Add((int.Parse(match.Groups["line"].Value), int.Parse(match.Groups["column"].Value)));
    }

    return result;
}

sealed class NullDefaultRewriter : CSharpSyntaxRewriter
{
    readonly HashSet<int> _diagnosticPositions;

    public NullDefaultRewriter(HashSet<int> diagnosticPositions)
    {
        _diagnosticPositions = diagnosticPositions;
    }

    public int ChangeCount { get; private set; }

    public override SyntaxNode? VisitParameter(ParameterSyntax node)
    {
        var visited = (ParameterSyntax)base.VisitParameter(node)!;
        var hasNullLiteral = visited.Default?.Value.IsKind(SyntaxKind.NullLiteralExpression) == true;
        var hasDefaultDiagnostic = visited.Default != null && _diagnosticPositions.Any(visited.Default.Span.Contains);
        if (visited.Type == null
            || visited.Type is NullableTypeSyntax
            || !hasNullLiteral && !hasDefaultDiagnostic)
            return visited;

        var originalType = visited.Type;
        var nullableType = SyntaxFactory.NullableType(originalType.WithoutTrailingTrivia())
            .WithTrailingTrivia(originalType.GetTrailingTrivia());
        ChangeCount++;
        return visited.WithType(nullableType);
    }
}
