#:package Microsoft.CodeAnalysis.CSharp
#:property Nullable=enable
#:property ImplicitUsings=enable
#:property PublishAot=false

using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

if (args.Length != 2 || args[0] is not ("analyze" or "apply" or "repair"))
{
    Console.Error.WriteLine("Usage: dotnet run tools/api-conventions/DocumentPublicApi.cs -- <analyze|apply|repair> <report.json>");
    return 2;
}

string mode = args[0];
string repositoryRoot = Directory.GetCurrentDirectory();
string sourceRoot = Path.Combine(repositoryRoot, "src");
string reportPath = Path.GetFullPath(args[1]);
if (!Directory.Exists(sourceRoot) || !File.Exists(Path.Combine(repositoryRoot, "ViciOne.ServiceBus.slnx")))
    throw new InvalidOperationException("Run this tool from the ViciOne.ServiceBus repository root.");

if (mode == "repair")
{
    var repairedFiles = new List<FileChange>();
    foreach (string file in Directory.EnumerateFiles(sourceRoot, "*.cs", SearchOption.AllDirectories)
                 .Where(static file => !HasExcludedSegment(file))
                 .Order(StringComparer.Ordinal))
    {
        string original = File.ReadAllText(file, Encoding.UTF8);
        string rewritten = RepairGeneratedDocumentation(original, file, out int repairs);
        if (repairs == 0)
            continue;

        File.WriteAllText(file, rewritten, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        repairedFiles.Add(new FileChange(Path.GetRelativePath(repositoryRoot, file).Replace('\\', '/'), repairs));
    }

    Directory.CreateDirectory(Path.GetDirectoryName(reportPath)!);
    var repairReport = new
    {
        generatedAtUtc = DateTimeOffset.UtcNow,
        mode,
        changedFiles = repairedFiles.Count,
        repairedDocumentationBlocks = repairedFiles.Sum(static change => change.Insertions),
        files = repairedFiles,
    };
    File.WriteAllText(reportPath, JsonSerializer.Serialize(repairReport, new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine);
    Console.WriteLine($"Repaired {repairReport.repairedDocumentationBlocks} generated documentation blocks in {repairReport.changedFiles} files.");
    Console.WriteLine($"Wrote {reportPath}");
    return 0;
}

var changes = new List<FileChange>();
foreach (string file in Directory.EnumerateFiles(sourceRoot, "*.cs", SearchOption.AllDirectories)
             .Where(static file => !HasExcludedSegment(file))
             .Order(StringComparer.Ordinal))
{
    string original = File.ReadAllText(file, Encoding.UTF8);
    if (original.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
        continue;

    SyntaxTree tree = CSharpSyntaxTree.ParseText(original, new CSharpParseOptions(LanguageVersion.Preview), file);
    SyntaxNode root = await tree.GetRootAsync();
    SourceText text = tree.GetText();
    var insertions = new List<Insertion>();

    foreach (SyntaxNode declaration in root.DescendantNodes().Where(IsDocumentableApiDeclaration))
    {
        if (HasDocumentation(declaration))
            continue;

        TextLine line = text.Lines.GetLineFromPosition(declaration.SpanStart);
        string indentation = text.ToString(TextSpan.FromBounds(line.Start, declaration.SpanStart));
        if (indentation.Any(static character => !char.IsWhiteSpace(character)))
            indentation = new string(' ', tree.GetLineSpan(declaration.Span).StartLinePosition.Character);

        insertions.Add(new Insertion(line.Start, CreateDocumentation(declaration, indentation)));
    }

    if (insertions.Count == 0)
        continue;

    string rewritten = original;
    foreach (Insertion insertion in insertions.OrderByDescending(static insertion => insertion.Position))
        rewritten = rewritten.Insert(insertion.Position, insertion.Text);

    string relative = Path.GetRelativePath(repositoryRoot, file).Replace('\\', '/');
    changes.Add(new FileChange(relative, insertions.Count));
    if (mode == "apply")
        File.WriteAllText(file, rewritten, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
}

Directory.CreateDirectory(Path.GetDirectoryName(reportPath)!);
var report = new
{
    generatedAtUtc = DateTimeOffset.UtcNow,
    mode,
    changedFiles = changes.Count,
    insertedDocumentationBlocks = changes.Sum(static change => change.Insertions),
    files = changes,
};
File.WriteAllText(reportPath, JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine);
Console.WriteLine($"{(mode == "apply" ? "Applied" : "Found")} {report.insertedDocumentationBlocks} documentation blocks in {report.changedFiles} files.");
Console.WriteLine($"Wrote {reportPath}");
return 0;

static bool HasExcludedSegment(string file)
{
    string normalized = file.Replace('\\', '/');
    return normalized.Contains("/bin/", StringComparison.Ordinal)
        || normalized.Contains("/obj/", StringComparison.Ordinal)
        || normalized.Contains("/artifacts/", StringComparison.Ordinal);
}

static string RepairGeneratedDocumentation(string original, string file, out int repairs)
{
    int replacementCount = 0;
    string rewritten = Regex.Replace(
        original,
        "Initializes a new instance of the <see cref=\\\"[^\\\"]+\\\" /> class\\.",
        match =>
        {
            replacementCount++;
            return "Initializes a new instance of the containing type.";
        });
    rewritten = ReplaceGeneratedPhrase(
        rewritten,
        "Provides (?:a|an) ([a-z0-9 ]+) exception implementation\\.",
        "Represents an error related to $1.",
        ref replacementCount);
    rewritten = ReplaceGeneratedPhrase(
        rewritten,
        "Provides (?:a|an) ([a-z0-9 ]+) options implementation\\.",
        "Defines configuration options for $1.",
        ref replacementCount);
    rewritten = ReplaceGeneratedPhrase(
        rewritten,
        "Provides (?:a|an) ([a-z0-9 ]+) extensions implementation\\.",
        "Provides extension methods for $1.",
        ref replacementCount);
    (string Old, string New)[] exactPhrases =
    [
        ("The value value.", "The value."),
        ("Gets the value value.", "Gets the underlying value."),
        ("Gets or sets the value value.", "Gets or sets the underlying value."),
        ("Performs the to string operation.", "Returns the string representation of this instance."),
        ("Performs the get hash code operation.", "Returns a hash code for this instance."),
        ("Performs the equals operation.", "Determines whether this instance equals the supplied value."),
        ("Performs the compare to operation.", "Compares this instance with the supplied value."),
        ("Performs the deconstruct operation.", "Deconstructs this value into its components."),
        ("Performs the dispose operation.", "Releases the resources owned by this instance."),
        ("Performs the dispose async operation.", "Releases the resources owned by this instance asynchronously."),
        ("Performs the apply operation.", "Applies this specification to the target builder."),
        ("Performs the validate operation.", "Validates the current configuration."),
        ("Performs the parse operation.", "Parses the supplied representation."),
        ("Performs the try parse operation.", "Attempts to parse the supplied representation."),
        ("Performs the consume operation.", "Consumes the message provided by the context."),
        ("Performs the send operation.", "Sends a message to the configured destination."),
        ("Performs the publish operation.", "Publishes a message to its configured consumers."),
        ("Performs the start operation.", "Starts the configured component."),
        ("Performs the stop operation.", "Stops the configured component."),
    ];
    foreach ((string oldPhrase, string newPhrase) in exactPhrases)
    {
        int occurrences = CountOccurrences(rewritten, oldPhrase);
        if (occurrences == 0)
            continue;
        rewritten = rewritten.Replace(oldPhrase, newPhrase, StringComparison.Ordinal);
        replacementCount += occurrences;
    }

    SyntaxTree tree = CSharpSyntaxTree.ParseText(rewritten, new CSharpParseOptions(LanguageVersion.Preview), file);
    SyntaxNode root = tree.GetRoot();
    SourceText text = tree.GetText();
    var linesToRemove = new HashSet<TextSpan>();

    foreach (MethodDeclarationSyntax method in root.DescendantNodes().OfType<MethodDeclarationSyntax>()
                 .Where(static method => method.ReturnType.ToString() == "void"))
    {
        CollectGeneratedElementLines(method, "returns", "The result of the operation.", text, linesToRemove);
    }

    foreach (TypeDeclarationSyntax type in root.DescendantNodes().OfType<TypeDeclarationSyntax>()
                 .Where(static type => type.Modifiers.Any(SyntaxKind.PartialKeyword)))
    {
        CollectGeneratedTypeParameterLines(type, text, linesToRemove);
    }

    foreach (TextSpan span in linesToRemove.OrderByDescending(static span => span.Start))
        rewritten = rewritten.Remove(span.Start, span.Length);
    repairs = replacementCount + linesToRemove.Count;
    return rewritten;
}

static string ReplaceGeneratedPhrase(string text, string pattern, string replacement, ref int replacementCount)
{
    replacementCount += Regex.Matches(text, pattern, RegexOptions.CultureInvariant).Count;
    return Regex.Replace(text, pattern, replacement, RegexOptions.CultureInvariant);
}

static void CollectGeneratedElementLines(
    SyntaxNode declaration,
    string elementName,
    string generatedText,
    SourceText text,
    ISet<TextSpan> lines)
{
    foreach (DocumentationCommentTriviaSyntax documentation in declaration.GetLeadingTrivia()
                 .Where(static trivia => trivia.HasStructure)
                 .Select(static trivia => trivia.GetStructure())
                 .OfType<DocumentationCommentTriviaSyntax>())
    {
        foreach (XmlElementSyntax element in documentation.DescendantNodes().OfType<XmlElementSyntax>())
        {
            if (element.StartTag.Name.LocalName.ValueText != elementName
                || !string.Equals(element.Content.ToFullString().Trim(), generatedText, StringComparison.Ordinal))
                continue;

            TextLine line = text.Lines.GetLineFromPosition(element.SpanStart);
            lines.Add(TextSpan.FromBounds(line.Start, line.EndIncludingLineBreak));
        }
    }
}

static void CollectGeneratedTypeParameterLines(SyntaxNode declaration, SourceText text, ISet<TextSpan> lines)
{
    foreach (DocumentationCommentTriviaSyntax documentation in declaration.GetLeadingTrivia()
                 .Where(static trivia => trivia.HasStructure)
                 .Select(static trivia => trivia.GetStructure())
                 .OfType<DocumentationCommentTriviaSyntax>())
    {
        foreach (XmlElementSyntax element in documentation.DescendantNodes().OfType<XmlElementSyntax>())
        {
            if (element.StartTag.Name.LocalName.ValueText != "typeparam"
                || !Regex.IsMatch(element.Content.ToFullString().Trim(), "^The [a-z0-9 ]+ type\\.$", RegexOptions.CultureInvariant))
                continue;

            TextLine line = text.Lines.GetLineFromPosition(element.SpanStart);
            lines.Add(TextSpan.FromBounds(line.Start, line.EndIncludingLineBreak));
        }
    }
}

static bool IsDocumentableApiDeclaration(SyntaxNode node)
{
    if (node is EnumMemberDeclarationSyntax)
        return node.Ancestors().OfType<EnumDeclarationSyntax>().FirstOrDefault() is { } enumeration
            && IsExternallyVisible(enumeration);

    if (node is not MemberDeclarationSyntax member || node is NamespaceDeclarationSyntax or FileScopedNamespaceDeclarationSyntax)
        return false;

    bool declaredVisible = member switch
    {
        BaseTypeDeclarationSyntax type => IsVisibleByModifiers(type.Modifiers, type.Parent),
        DelegateDeclarationSyntax declaration => IsVisibleByModifiers(declaration.Modifiers, declaration.Parent),
        BaseMethodDeclarationSyntax method => IsVisibleByModifiers(method.Modifiers, method.Parent),
        BasePropertyDeclarationSyntax property => IsVisibleByModifiers(property.Modifiers, property.Parent),
        BaseFieldDeclarationSyntax field => IsVisibleByModifiers(field.Modifiers, field.Parent),
        _ => false,
    };

    return declaredVisible && IsExternallyVisible(member);
}

static bool IsExternallyVisible(SyntaxNode declaration)
{
    foreach (MemberDeclarationSyntax container in declaration.Ancestors().OfType<MemberDeclarationSyntax>())
    {
        if (container is BaseTypeDeclarationSyntax type && !IsVisibleByModifiers(type.Modifiers, type.Parent))
            return false;
        if (container is DelegateDeclarationSyntax delegateDeclaration
            && !IsVisibleByModifiers(delegateDeclaration.Modifiers, delegateDeclaration.Parent))
            return false;
    }
    return true;
}

static bool IsVisibleByModifiers(SyntaxTokenList modifiers, SyntaxNode? parent)
{
    if (modifiers.Any(SyntaxKind.PrivateKeyword))
        return false;
    if (modifiers.Any(SyntaxKind.PublicKeyword) || modifiers.Any(SyntaxKind.ProtectedKeyword))
        return true;

    return parent is InterfaceDeclarationSyntax;
}

static bool HasDocumentation(SyntaxNode declaration) => declaration
    .GetLeadingTrivia()
    .Any(static trivia => trivia.HasStructure && trivia.GetStructure() is DocumentationCommentTriviaSyntax);

static string CreateDocumentation(SyntaxNode declaration, string indentation)
{
    var lines = new List<string>
    {
        $"{indentation}/// <summary>",
        $"{indentation}/// {Summary(declaration)}",
        $"{indentation}/// </summary>",
    };

    foreach (TypeParameterSyntax typeParameter in TypeParameters(declaration))
        lines.Add($"{indentation}/// <typeparam name=\"{typeParameter.Identifier.ValueText}\">The {Xml(Humanize(typeParameter.Identifier.ValueText))} type.</typeparam>");

    foreach (ParameterSyntax parameter in Parameters(declaration))
        lines.Add($"{indentation}/// <param name=\"{parameter.Identifier.ValueText}\">{ParameterDescription(parameter.Identifier.ValueText)}</param>");

    if (ReturnsValue(declaration))
        lines.Add($"{indentation}/// <returns>{ReturnDescription(declaration)}</returns>");

    return string.Join(Environment.NewLine, lines) + Environment.NewLine;
}

static string Summary(SyntaxNode declaration)
{
    return declaration switch
    {
        ClassDeclarationSyntax type when type.Identifier.ValueText.EndsWith("Exception", StringComparison.Ordinal) =>
            $"Represents an error related to {Humanize(type.Identifier.ValueText[..^"Exception".Length])}.",
        ClassDeclarationSyntax type when type.Identifier.ValueText.EndsWith("Options", StringComparison.Ordinal) =>
            $"Defines configuration options for {Humanize(type.Identifier.ValueText[..^"Options".Length])}.",
        ClassDeclarationSyntax type when type.Identifier.ValueText.EndsWith("Extensions", StringComparison.Ordinal) =>
            $"Provides extension methods for {Humanize(type.Identifier.ValueText[..^"Extensions".Length])}.",
        ClassDeclarationSyntax type => $"Provides {Article(Humanize(type.Identifier.ValueText))} implementation.",
        InterfaceDeclarationSyntax type => $"Defines the contract for {Humanize(TrimInterfacePrefix(type.Identifier.ValueText))}.",
        RecordDeclarationSyntax type => $"Represents {Article(Humanize(type.Identifier.ValueText))} value.",
        StructDeclarationSyntax type => $"Represents {Article(Humanize(type.Identifier.ValueText))} value.",
        EnumDeclarationSyntax type => $"Specifies the available {Humanize(type.Identifier.ValueText)} values.",
        DelegateDeclarationSyntax type => $"Represents the method that handles {Humanize(type.Identifier.ValueText)}.",
        ConstructorDeclarationSyntax => "Initializes a new instance of the containing type.",
        MethodDeclarationSyntax method => MethodSummary(method.Identifier.ValueText),
        OperatorDeclarationSyntax operation => $"Applies the <c>{Xml(operation.OperatorToken.ValueText)}</c> operator.",
        ConversionOperatorDeclarationSyntax => "Converts a value to the target type.",
        PropertyDeclarationSyntax property => PropertySummary(property.Identifier.ValueText, property.AccessorList),
        IndexerDeclarationSyntax => "Gets or sets the value at the specified index.",
        EventDeclarationSyntax eventDeclaration => $"Occurs when {Humanize(eventDeclaration.Identifier.ValueText)}.",
        EventFieldDeclarationSyntax eventField => $"Occurs when {Humanize(eventField.Declaration.Variables.First().Identifier.ValueText)}.",
        FieldDeclarationSyntax field => $"Defines the {Humanize(field.Declaration.Variables.First().Identifier.ValueText)} value.",
        EnumMemberDeclarationSyntax member => $"Indicates {Humanize(member.Identifier.ValueText)}.",
        _ => "Defines a public service bus API member.",
    };
}

static string MethodSummary(string name)
{
    string operation = name.EndsWith("Async", StringComparison.Ordinal) ? name[..^5] : name;
    IReadOnlyDictionary<string, string> exactOperations = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Consume"] = "Consumes the message provided by the context.",
        ["Send"] = "Sends a message to the configured destination.",
        ["Publish"] = "Publishes a message to its configured consumers.",
        ["Start"] = "Starts the configured component.",
        ["Stop"] = "Stops the configured component.",
        ["Validate"] = "Validates the current configuration.",
        ["Apply"] = "Applies this specification to the target builder.",
        ["Dispose"] = "Releases the resources owned by this instance.",
        ["ToString"] = "Returns the string representation of this instance.",
        ["GetHashCode"] = "Returns a hash code for this instance.",
        ["Equals"] = "Determines whether this instance equals the supplied value.",
        ["Deconstruct"] = "Deconstructs this value into its components.",
    };
    if (exactOperations.TryGetValue(operation, out string? exactSummary))
        return exactSummary;
    (string Prefix, string Verb, string Suffix)[] verbs =
    [
        ("TryGet", "Attempts to get", "."),
        ("Add", "Adds", " to the configuration."),
        ("Configure", "Configures", "."),
        ("Connect", "Connects", "."),
        ("Create", "Creates", "."),
        ("Get", "Gets", "."),
        ("Set", "Sets", "."),
        ("Use", "Configures", " for the current pipeline."),
        ("Send", "Sends", "."),
        ("Publish", "Publishes", "."),
        ("Consume", "Consumes", "."),
        ("Schedule", "Schedules", "."),
        ("Start", "Starts", "."),
        ("Stop", "Stops", "."),
        ("Validate", "Validates", "."),
        ("Is", "Determines whether", "."),
        ("Has", "Determines whether the current value has", "."),
        ("Can", "Determines whether the current value can", "."),
    ];
    foreach ((string prefix, string verb, string suffix) in verbs)
    {
        if (operation.StartsWith(prefix, StringComparison.Ordinal) && operation.Length > prefix.Length)
            return $"{verb} {Humanize(operation[prefix.Length..])}{suffix}";
    }
    return $"Performs the {Humanize(operation)} operation.";
}

static string PropertySummary(string name, AccessorListSyntax? accessors)
{
    bool canSet = accessors?.Accessors.Any(static accessor => accessor.IsKind(SyntaxKind.SetAccessorDeclaration)
        || accessor.IsKind(SyntaxKind.InitAccessorDeclaration)) == true;
    return $"Gets{(canSet ? " or sets" : string.Empty)} the {Humanize(name)} value.";
}

static IEnumerable<TypeParameterSyntax> TypeParameters(SyntaxNode declaration) => declaration switch
{
    TypeDeclarationSyntax type => type.TypeParameterList?.Parameters ?? [],
    DelegateDeclarationSyntax delegateDeclaration => delegateDeclaration.TypeParameterList?.Parameters ?? [],
    MethodDeclarationSyntax method => method.TypeParameterList?.Parameters ?? [],
    _ => [],
};

static IEnumerable<ParameterSyntax> Parameters(SyntaxNode declaration) => declaration switch
{
    BaseMethodDeclarationSyntax method => method.ParameterList.Parameters,
    DelegateDeclarationSyntax delegateDeclaration => delegateDeclaration.ParameterList.Parameters,
    IndexerDeclarationSyntax indexer => indexer.ParameterList.Parameters,
    _ => [],
};

static bool ReturnsValue(SyntaxNode declaration) => declaration switch
{
    MethodDeclarationSyntax method => method.ReturnType.ToString() != "void",
    OperatorDeclarationSyntax => true,
    ConversionOperatorDeclarationSyntax => true,
    DelegateDeclarationSyntax delegateDeclaration => !delegateDeclaration.ReturnType.IsKind(SyntaxKind.VoidKeyword),
    _ => false,
};

static string ReturnDescription(SyntaxNode declaration)
{
    TypeSyntax? returnType = declaration switch
    {
        MethodDeclarationSyntax method => method.ReturnType,
        OperatorDeclarationSyntax operation => operation.ReturnType,
        ConversionOperatorDeclarationSyntax operation => operation.Type,
        DelegateDeclarationSyntax delegateDeclaration => delegateDeclaration.ReturnType,
        _ => null,
    };
    if (returnType?.ToString() is "bool" or "System.Boolean")
        return "<see langword=\"true\" /> when the condition is satisfied; otherwise, <see langword=\"false\" />.";
    return "The result of the operation.";
}

static string ParameterDescription(string name) => name switch
{
    "cancellationToken" => "The token used to cancel the operation.",
    "configure" or "configuration" => "The configuration callback.",
    "context" => "The operation context.",
    "services" => "The dependency-injection service collection.",
    "provider" => "The service provider.",
    "exception" => "The exception associated with the operation.",
    _ => $"The {Xml(Humanize(name))} value.",
};

static string TrimInterfacePrefix(string name) =>
    name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]) ? name[1..] : name;

static string Humanize(string value)
{
    string text = value.TrimStart('@').Replace('_', ' ');
    text = Regex.Replace(text, "([A-Z]+)([A-Z][a-z])", "$1 $2");
    text = Regex.Replace(text, "([a-z0-9])([A-Z])", "$1 $2");
    return Xml(text.ToLowerInvariant());
}

static string Article(string phrase) =>
    phrase.Length > 0 && "aeiou".Contains(phrase[0]) ? $"an {phrase}" : $"a {phrase}";

static string Xml(string value) => value
    .Replace("&", "&amp;", StringComparison.Ordinal)
    .Replace("<", "&lt;", StringComparison.Ordinal)
    .Replace(">", "&gt;", StringComparison.Ordinal)
    .Replace("\"", "&quot;", StringComparison.Ordinal);

static int CountOccurrences(string value, string fragment)
{
    int count = 0;
    int offset = 0;
    while ((offset = value.IndexOf(fragment, offset, StringComparison.Ordinal)) >= 0)
    {
        count++;
        offset += fragment.Length;
    }
    return count;
}

internal sealed record Insertion(int Position, string Text);
internal sealed record FileChange(string File, int Insertions);
