<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTags>ViciOne.ServiceBus;SignalR</PackageTags>
    <Description>ViciOne.ServiceBus SignalR Backplane support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != 'net472'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
  </ItemGroup>

</Project>
