<!-- ViciOne modification: WP-F2-SERVICEBUS-IDENTITY, 2026-08-07. -->
<Project>
  <Import Project="..\Directory.Build.props"/>

  <PropertyGroup>
    <Product>ViciOne.ServiceBus</Product>
    <Copyright>Copyright 2007-2024 Chris Patterson</Copyright>
    <Authors>Chris Patterson</Authors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugSymbols>True</DebugSymbols>
    <NoWarn>$(NoWarn)</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <PackageIcon>vicione-servicebus-logo.png</PackageIcon>
    <PackageReadmeFile>NuGet.README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/EdgarLiebold/vicione-servicebus</PackageProjectUrl>
    <Description>ViciOne.ServiceBus provides a developer-focused, modern platform for creating distributed applications without complexity.</Description>
    <IsPackable>True</IsPackable>

    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\vicione-servicebus-logo.png" Pack="true" Visible="false" PackagePath=""/>
    <None Include="..\..\NuGet.README.md" Pack="true" Visible="false" PackagePath=""/>
  </ItemGroup>

</Project>
