<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Scheduling/ViciOne.ServiceBus.QuartzIntegration/ViciOne.ServiceBus.QuartzIntegration.csproj" />
    <ProjectReference Include="../../Testing/ViciOne.ServiceBus.Tests.Infrastructure/ViciOne.ServiceBus.Tests.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Requirements/QuartzInheritedBehaviorDisposition.json" />
    <None Remove="Requirements/QuartzIntegrationRequirements.json" />
    <EmbeddedResource
      Include="Requirements/QuartzInheritedBehaviorDisposition.json"
      LogicalName="ViciOne.ServiceBus.QuartzIntegration.Tests.Requirements.QuartzInheritedBehaviorDisposition.json" />
    <EmbeddedResource
      Include="Requirements/QuartzIntegrationRequirements.json"
      LogicalName="ViciOne.ServiceBus.QuartzIntegration.Tests.Requirements.QuartzIntegrationRequirements.json" />
  </ItemGroup>

</Project>
