<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Denys Kozhevnikov, $(Authors)</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>ViciOne.ServiceBus.EventHubs</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ViciOne.ServiceBus.EventHubs</PackageId>
    <Title>ViciOne.ServiceBus.EventHubs</Title>
    <PackageTags>ViciOne.ServiceBus;EventHub</PackageTags>
    <Description>ViciOne.ServiceBus EventHub Support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <ProjectReference Include="..\..\ViciOne.ServiceBus\ViciOne.ServiceBus.csproj" />
    <ProjectReference Include="..\..\ViciOne.ServiceBus.Sagas\ViciOne.ServiceBus.Sagas.csproj" />
  </ItemGroup>

</Project>
